services:
  - type: web
    name: nexstore
    runtime: node
    region: oregon
    plan: free
    buildCommand: npm install --include=dev && npm run build
    startCommand: npm run start
    envVars:
      - key: NODE_ENV
        value: production
      - key: EXTERNAL_DATABASE_URL
        sync: false
      - key: DATABASE_URL
        sync: false
      - key: SESSION_SECRET
        generateValue: true
      - key: RESEND_API_KEY
        sync: false
    healthCheckPath: /api/settings
